### ISSUE TITLE
只翻译了标题，内容没翻译

### ISSUE THREAD

**Issue by yaoshengv** [tjsky/RSS-Translation#3]
![image](https://github.com/tjsky/RSS-Translation/assets/51487614/6719d821-a25c-4ed1-89ea-71babe14e990)

https://www.ted.com/feeds/talks.rss

**Comment by chinobing** [comment]
修改代码部分：
从`content= str(soup)`改为下面
```
    content= str(soup).replace("<![CDATA[","").replace("]]>","")

```
